### ISSUE TITLE
Recent message is not shown in chat list screen when user is added to an existing channel

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-swiftui#41]
## What did you do?
In our app, users are added to channels from admin panel which call the server to execute `addMembers` on different channels.

Use case:
Step 1: Keep the app open as all channels of user are visible in chat list screen
Step 2: Add user to a existing channel with messages using addMembers method call from server

## What did you expect to happen?
Expectation was that the chat list screen would update and that particular channel will be added with correct data, including the recent message shown below channel name.

## What happened instead?
The channel was added with correct profile photo and channel name but instead of the recent message it showed `No messages` below channel name.

## GetStream Environment
**GetStream Chat version:** Using from master branch
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 14.8.1
**Swift version:** Swift 5
**Xcode version:** 13.2.1
**Device:** iPhone 11

**Comment by martinmitrevski** [comment]
Hey @JayMehta97,

Thanks for reporting this. We've started analysing the issue and as soon as we have an update, we'll post it here.

**Comment by martinmitrevski** [comment]
Hey @JayMehta97,

This one is also fixed now and available on `main`.

**Comment by JayMehta97** [comment]
Hey @martinmitrevski ,

I tried the latest code from `main` but I am still facing this issue.

**Comment by martinmitrevski** [comment]
@JayMehta97 this one is also not reproducible for us atm. Are you doing any custom implementation with the channel list items? More details would be very helpful. 

Also, are you still able to reproduce it with our demo app?

**Comment by martinmitrevski** [comment]
As discussed, this is a bug in our low-level SDK. As soon as we have an update, I will post it here.

**Comment by martinmitrevski** [comment]
Hey @JayMehta97, 

The issue was resolved in our low-level SDK. It's now available on `main`, and it will be released later today.

Regards,
Martin
