### ISSUE TITLE
Not possible to dismiss keyboard when coming from empty state

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swiftui#481]
## What did you do?
* Present a ChatChannelView of a channel without any messages and a custom empty view with the keyboard up.
* Send a message
* Trying to dismiss the keyboard swiping down or tapping on the background doesn't work forcing to dismiss and open the chat again for it to work

## What did you expect to happen?
* Dismissal behavior should work regardless if it's coming from an empty state or not.

## What happened instead?
It seems that the flag `@State private var keyboardShown = false` in MessageListView when switching from empty to having messages it remains in false since there is no keyboard trigger. 

So the logic in line 239 of MessageListView doesn't trigger in this scenario.
`    if keyboardShown && diff < -20 {
                            keyboardShown = false
                            resignFirstResponder()
                        }
                        if offsetValue > 5 {
                            onMessageAppear(0, .down)
                        }`
                        
## GetStream Environment
**GetStream Chat version:** 4.54.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.4
**Swift version:**  >5
**Xcode version:** 15.3
**Device:** iphone 15

**Comment by laevandus** [comment]
Hi @fceldeiro This issue is fixed in [4.58.0](https://github.com/GetStream/stream-chat-swiftui/releases/tag/4.58.0) Thank you for reporting!

**Comment by fceldeiro** [comment]
Hello @laevandus , i've just tried 4.58.0 and the issue remains. If the keyboard is up when sending a message in a chat without messages i cannot dismiss the keyboard while swiping after.
